version: '3.8'

services:
  funasr-service:
    build: .
    container_name: funasr_server
    restart: always
    ports:
      - "10095:10095"
    volumes:
      # 将模型缓存映射到宿主机，避免容器重启后重新下载 2.3GB 的模型
      - ./temp_asr_models:/app/temp_asr_models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - ASR_AUTO_START=true
